version: "3.7"

services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - mynet
    command: "yarn start:dev"

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - mynet

  redis:
    command: redis-server --port 6379
    image: redis
    environment:
      - REDIS_DATA_DIR=/data/redis
    ports:
      - "6379:6379"
    networks:
      - mynet

  sentry:
    container_name: sentry
    image: sentry
    depends_on:
      - redis
      - postgres
    ports:
      - 9000:9000
    env_file:
      - ./.env
    networks:
      - mynet

  cron:
    image: sentry
    depends_on:
      - redis
      - postgres
    command: "sentry run cron"
    env_file:
      - ./.env
    networks:
      - mynet

  worker:
    image: sentry
    depends_on:
      - redis
      - postgres
    command: "sentry run worker"
    env_file:
      - ./.env
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet:
